/* Generated By:JavaCC: Do not edit this line. Regex2AutoTreeConstants.java Version 5.0 */
public interface Regex2AutoTreeConstants
{
  public int JJTEXP = 0;
  public int JJTCHAR = 1;
  public int JJTMULTIPLICITY = 2;
  public int JJTSTART = 3;


  public String[] jjtNodeName = {
    "EXP",
    "Char",
    "Multiplicity",
    "Start",
  };
}
/* JavaCC - OriginalChecksum=7061c03d6cc305fd1c3a9b546630bb33 (do not edit this line) */
