/* Generated By:JavaCC: Do not edit this line. Regex2AutoTreeConstants.java Version 5.0 */
public interface Regex2AutoTreeConstants
{
  public int JJTEXP = 0;
  public int JJTANYCHAR = 1;
  public int JJTCHARVAL = 2;
  public int JJTMULTIPLICITY = 3;
  public int JJTZEROMORE = 4;
  public int JJTONEMORE = 5;
  public int JJTZEROONE = 6;
  public int JJTRUN = 7;


  public String[] jjtNodeName = {
    "EXP",
    "AnyChar",
    "charval",
    "Multiplicity",
    "zeromore",
    "onemore",
    "zeroone",
    "run",
  };
}
/* JavaCC - OriginalChecksum=11b49d2c8ee28af91f50fedce13c97f1 (do not edit this line) */
