import java.util.concurrent.atomic.AtomicInteger;

/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 4.3 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class SimpleNode implements Node {

	protected Node parent;
	protected Node[] children;
	protected int id;
	protected Object value;
	protected Regex2Auto parser;
	protected int stateID;

	public SimpleNode(int i) {
		id = i;
		stateID = -1;
	}

	public SimpleNode(Regex2Auto p, int i) {
		this(i);
		parser = p;
	}

	public void jjtOpen() {
	}

	public void jjtClose() {
	}

	public void jjtSetParent(Node n) {
		parent = n;
	}

	public Node jjtGetParent() {
		return parent;
	}

	public void jjtAddChild(Node n, int i) {
		if (children == null) {
			children = new Node[i + 1];
		} else if (i >= children.length) {
			Node c[] = new Node[i + 1];
			System.arraycopy(children, 0, c, 0, children.length);
			children = c;
		}
		children[i] = n;
	}

	public Node jjtGetChild(int i) {
		return children[i];
	}

	public int jjtGetPositionInParent() {
		Node parent = jjtGetParent();
		for (int i = 0; i < parent.jjtGetNumChildren(); i++)
			if (parent.jjtGetChild(i) == this)
				return i;
		return -1;
	}

	public Node jjtGetPreviousSibling() {
		int pos = jjtGetPositionInParent();
		if (pos == -1)
			return null;
		else
			return parent.jjtGetChild(pos - 1);
	}
	
	public Node jjtGetFirstStateNode() { //Gets the first node inside a parenthesis which is a valid state
		try{
		if(this.getStateID()>-1)
			return this;
		else
			return ((SimpleNode)this.jjtGetChild(0)).jjtGetFirstStateNode();
		}
		catch(NullPointerException e){
			System.out.println("ESTOUROU");
			return null;
		}
	}

	public int jjtGetNumChildren() {
		return (children == null) ? 0 : children.length;
	}

	public void jjtSetValue(Object value) {
		this.value = value;
	}

	public Object jjtGetValue() {
		return value;
	}

	public int getStateID() {
		return stateID;
	}

	/*
	 * You can override these two methods in subclasses of SimpleNode to
	 * customize the way the node appears when the tree is dumped. If your
	 * output uses more than one line you should override toString(String),
	 * otherwise overriding toString() is probably all you need to do.
	 */

	public String toString() {
		String ret = Regex2AutoTreeConstants.jjtNodeName[id];
		if (this.jjtGetValue() != null)
			ret += " " + this.jjtGetValue().toString();
		return ret;
	}

	public String toString(String prefix) {
		return prefix + toString();
	}

	public void generateAutomaton(Automaton a) {
		int nextStateID = a.getNumStates();
		State sourceState, destinationState;
		char transitionChar;
		switch (Regex2AutoTreeConstants.jjtNodeName[id]) {
		case "Start":
			a.addState(new State(nextStateID)); //Start state
			break;
		case "Multiplicity":
			switch (this.jjtGetValue().toString()) {
			case "*":
				break;
			case "+":
				break;
			case "?":
				break;
			}
			SimpleNode prevSibling = (SimpleNode) jjtGetPreviousSibling();
			SimpleNode stateNode = (SimpleNode)prevSibling.jjtGetFirstStateNode(); //first node which is not a parenthesis
			sourceState = a.getState(stateNode.getStateID()); //source state
			destinationState = sourceState; //destination state (same as source node)
			transitionChar = stateNode.jjtGetValue().toString().charAt(0); //get transition char
			sourceState.addConnection(destinationState, transitionChar);
			break;
		case "Char":
			this.stateID = nextStateID; //add stateID to node
			State newState = new State(this.stateID);
			a.addState(newState);
			sourceState = a.getState(nextStateID-1); //source state (previously inserted one)
			destinationState = newState; //destination state (the one inserted just now)
			transitionChar = this.jjtGetValue().toString().charAt(0); //get transition char
			sourceState.addConnection(destinationState, transitionChar);
			sourceState.setFinalState(false); //previous state is not final
			newState.setFinalState(true); //new state is final
			break;
		}
		if (children != null) {
			for (int i = 0; i < children.length; i++) {
				SimpleNode n = (SimpleNode) children[i];
				n.generateAutomaton(a);
			}
		}
	}

	/*
	 * Override this method if you want to customize how the node dumps out its
	 * children.
	 */

	public void dump(String prefix) {
		/*
		 * if(this.val!=null) System.out.println(prefix+this.val); else
		 */
		/*
		 * switch(this.id) { case Regex2AutoTreeConstants.JJTZEROMORE:
		 * System.out.println(prefix+jjtGetValue());break; case
		 * Regex2AutoTreeConstants.JJTONEMORE:
		 * System.out.println(prefix+"+");break; case
		 * Regex2AutoTreeConstants.JJTZEROONE:
		 * System.out.println(prefix+"?");break; case
		 * Regex2AutoTreeConstants.JJTCHARVAL:
		 * System.out.println(prefix+val);break; default:
		 * System.out.println(toString(prefix));break; }
		 */
		System.out.println(toString(prefix));

		if (children != null) {
			for (int i = 0; i < children.length; ++i) {
				SimpleNode n = (SimpleNode) children[i];
				if (n != null) {
					n.dump(prefix + " ");
				}
			}
		}
	}
}

/*
 * JavaCC - OriginalChecksum=c182086b4a6c2ffa42add9568197005b (do not edit this
 * line)
 */
